# Generated by Django 5.0 on 2023-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituredefect',
            name='id',
        ),
        migrations.AddField(
            model_name='furnituredefect',
            name='defect_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
